# Site settings
title: hjw99868 | Jiawei Hou
description: "A mini blog of mine."
url: "https://hjw99868.github.io"
author:
  name: "Jiawei Hou"
  email: "hjw99868@163.com"
  url: "https://hjw99868.github.io"

# Build settings
baseurl: "/"
url: ""
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate

# Options
custom_header: false
custom_nav_footer: false
reverse: false
